//! A scenario is a value: generated by proptest, shrunk to a minimum, and
//! checked in as a pinned file.

use std::collections::BTreeMap;

use aether_bloomery::{BloomId, CandidateRef, Digest, StageId, VerifyFailureSet, WorkpieceId};

/// One generated or pinned coordinator run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Scenario {
    /// Members of the sealed bloom, 1..=4 in the generator.
    pub members: Vec<MemberSpec>,
    /// Members armed with a fold collision at the fold.
    pub collide: Vec<WorkpieceId>,
    /// Optional supersede point: when, plus adopt / eject sets.
    pub supersede: Option<Supersede>,
    /// Operator moves, each at a step index.
    pub operator: Vec<OperatorMove>,
}

/// One sealed member.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemberSpec {
    /// The workpiece the member covers.
    pub workpiece: WorkpieceId,
    /// Declared-surface globs over the fixture project.
    pub surface: Vec<String>,
    /// Per-stage, per-occurrence lane scripts.
    pub script: BTreeMap<StageId, Vec<LaneScript>>,
}

/// What one lane occurrence does.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LaneScript {
    /// Pass, capturing a tree.
    Candidate,
    /// Concluded, no candidate — the `ConstructDeclined` route.
    Decline,
    /// Concluded, no candidate, and named the declared-surface path its work
    /// requires (ADR-0207) — the `Fact::SurfaceRequested` route. The path is
    /// the mock lane's canned one
    /// ([`aether_chassis_bloomery::bloomery::mock_lane::REQUESTED_PATH`]), a
    /// crate the fixture project has and no member surface covers.
    DeclineRequestingSurface,
    /// A candidate touching a path no glob covers.
    OutsideSurface(String),
    /// The lane process exits without evidence.
    Die,
    /// Evidence bound to a digest the order did not display.
    WrongSubject,
    /// A mechanical gate names these failed verifiers.
    VerifyFail(VerifyFailureSet),
    /// The bloom-less `verify.base` fan-out names these failed verifiers.
    BaseVerifyFail(VerifyFailureSet),
}

/// When and how a successor replaces the sealed bloom.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Supersede {
    /// Tick index at which the supersede is admitted.
    pub at_tick: u32,
    /// Members re-admitted at the same scope revision (inherit the claim).
    pub adopt: Vec<WorkpieceId>,
    /// Members omitted from the successor (ejected).
    pub eject: Vec<WorkpieceId>,
}

/// An operator fact admitted at a step index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OperatorMove {
    /// [`aether_bloomery::Fact::GrantAttempts`].
    Grant {
        /// Tick index.
        at_tick: u32,
        /// Member the grant names.
        workpiece: WorkpieceId,
        /// The stage the extra attempts are spent at. Named rather than derived
        /// from the member's cursor: a grant is an operator's statement about
        /// one stage's budget, and reading the cursor would silently aim it
        /// wherever the member happened to be when the tick landed.
        stage: StageId,
        /// Extra attempts.
        attempts: u32,
    },
    /// [`aether_bloomery::Fact::OperatorHold`].
    Hold {
        /// Tick index.
        at_tick: u32,
        /// Bloom the hold names; `None` means the sealed bloom.
        bloom: Option<BloomId>,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
    /// [`aether_bloomery::Fact::OperatorRelease`].
    Release {
        /// Tick index.
        at_tick: u32,
        /// Bloom the release names; `None` means the sealed bloom.
        bloom: Option<BloomId>,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
    /// [`aether_bloomery::Fact::OperatorRepair`].
    Repair {
        /// Tick index.
        at_tick: u32,
        /// Member the repair names.
        workpiece: WorkpieceId,
        /// The tree the operator is handing in, and the commit carrying it.
        candidate: CandidateRef,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
    /// [`aether_bloomery::Fact::Withdraw`] — take one member out of the
    /// walking bloom without superseding it (#5327). Appended for the reason
    /// the wire additions are appended.
    Withdraw {
        /// Tick index.
        at_tick: u32,
        /// Member the withdrawal names.
        workpiece: WorkpieceId,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
        /// Also withdraw every member that depends on this one. Without it, a
        /// withdrawal that would strand a dependent is refused, naming them.
        cascade: bool,
    },
    /// Grant one member the wider declared surface it asked for (ADR-0207).
    ///
    /// Lowers to [`aether_bloomery::Fact::Supersede`], because a sealed bloom's
    /// membership is frozen: the amended member enters a successor at its new
    /// scope revision and every sibling is carried across at the revision it
    /// already holds, inheriting its claim and its finished work. Appended for
    /// the reason the wire additions are appended.
    Amend {
        /// Tick index.
        at_tick: u32,
        /// The member whose surface is widened.
        workpiece: WorkpieceId,
        /// The widened revision's digest — what the successor admits the member
        /// at, and what the containment check reads its surface out of.
        scope_revision: Digest,
    },
    /// [`aether_bloomery::Fact::ProposeChange`] — a signed operator change
    /// waiting for a clear board (ADR-0205). Appended for the reason the
    /// harness's other additions are appended.
    Propose {
        /// Tick index.
        at_tick: u32,
        /// The tree the operator is handing in, and the commit carrying it.
        candidate: CandidateRef,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
}

impl Scenario {
    /// A single-member bloom whose every lane passes.
    #[must_use]
    pub fn passing(workpiece: impl Into<String>) -> Self {
        Self {
            members: vec![MemberSpec {
                workpiece: WorkpieceId(workpiece.into()),
                surface: vec!["crates/example-a/**".into()],
                script: BTreeMap::new(),
            }],
            collide: Vec::new(),
            supersede: None,
            operator: Vec::new(),
        }
    }
}
