//! A scenario is a value: generated by proptest, shrunk to a minimum, and
//! checked in as a pinned file.

use std::collections::BTreeMap;

use aether_bloomery::{BloomId, StageId, VerifyFailureSet, WorkpieceId};

/// One generated or pinned coordinator run.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Scenario {
    /// Members of the sealed bloom, 1..=4 in the generator.
    pub members: Vec<MemberSpec>,
    /// Members armed with a fold collision at the fold.
    pub collide: Vec<WorkpieceId>,
    /// Optional supersede point: when, plus adopt / eject sets.
    pub supersede: Option<Supersede>,
    /// Operator moves, each at a step index.
    pub operator: Vec<OperatorMove>,
}

/// One sealed member.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemberSpec {
    /// The workpiece the member covers.
    pub workpiece: WorkpieceId,
    /// Declared-surface globs over the fixture project.
    pub surface: Vec<String>,
    /// Per-stage, per-occurrence lane scripts.
    pub script: BTreeMap<StageId, Vec<LaneScript>>,
}

/// What one lane occurrence does.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LaneScript {
    /// Pass, capturing a tree.
    Candidate,
    /// Concluded, no candidate — the `ConstructDeclined` route.
    Decline,
    /// Concluded, no candidate, and named the declared-surface path its work
    /// requires (ADR-0207) — the `Fact::SurfaceRequested` route. The path is
    /// the mock lane's canned one
    /// ([`aether_chassis_bloomery::bloomery::mock_lane::REQUESTED_PATH`]), a
    /// crate the fixture project has and no member surface covers.
    DeclineRequestingSurface,
    /// A candidate touching a path no glob covers.
    OutsideSurface(String),
    /// The lane process exits without evidence.
    Die,
    /// Evidence bound to a digest the order did not display.
    WrongSubject,
    /// A mechanical gate names these failed verifiers.
    VerifyFail(VerifyFailureSet),
}

/// When and how a successor replaces the sealed bloom.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Supersede {
    /// Tick index at which the supersede is admitted.
    pub at_tick: u32,
    /// Members re-admitted at the same scope revision (inherit the claim).
    pub adopt: Vec<WorkpieceId>,
    /// Members omitted from the successor (ejected).
    pub eject: Vec<WorkpieceId>,
}

/// An operator fact admitted at a step index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OperatorMove {
    /// [`aether_bloomery::Fact::GrantAttempts`].
    Grant {
        /// Tick index.
        at_tick: u32,
        /// Member the grant names.
        workpiece: WorkpieceId,
        /// Extra attempts.
        attempts: u32,
    },
    /// [`aether_bloomery::Fact::OperatorHold`].
    Hold {
        /// Tick index.
        at_tick: u32,
        /// Bloom the hold names; `None` means the sealed bloom.
        bloom: Option<BloomId>,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
    /// [`aether_bloomery::Fact::OperatorRelease`].
    Release {
        /// Tick index.
        at_tick: u32,
        /// Bloom the release names; `None` means the sealed bloom.
        bloom: Option<BloomId>,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
    /// [`aether_bloomery::Fact::OperatorRepair`].
    Repair {
        /// Tick index.
        at_tick: u32,
        /// Member the repair names.
        workpiece: WorkpieceId,
        /// Why.
        reason: String,
        /// Who.
        operator: String,
    },
}

impl Scenario {
    /// A single-member bloom whose every lane passes.
    #[must_use]
    pub fn passing(workpiece: impl Into<String>) -> Self {
        Self {
            members: vec![MemberSpec {
                workpiece: WorkpieceId(workpiece.into()),
                surface: vec!["crates/example-a/**".into()],
                script: BTreeMap::new(),
            }],
            collide: Vec::new(),
            supersede: None,
            operator: Vec::new(),
        }
    }
}
