//! Bakes `assets/ear-voxels.json` into a generated Rust table.
//!
//! The extraction that produced the JSON is documented in
//! `assets/extraction-notes.md`. Parsing happens here, on the host, so the
//! shipped wasm carries the voxels as a static array and links no JSON parser —
//! and, more importantly, needs no filesystem at runtime: a component that had
//! to `aether.fs.read` its own geometry could not pose anything until an async
//! reply landed.
//!
//! The generated file is deliberately dumb — constants and one flat `[u8; 4]`
//! table. Every interpretation of those numbers (which axis is up, where the
//! bones sit, how a label becomes a color) lives in the crate proper, where it
//! is readable and testable.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

/// Read one of the variables cargo sets for a build script. Build scripts are
/// the carve-out the workspace's disallowed-`env::var` rule names explicitly:
/// these are not capability configuration, they are cargo's only channel for
/// telling a build script where it is.
#[allow(clippy::disallowed_methods)] // Cargo's build-script protocol, not cap config.
fn cargo_var(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("cargo sets {name} for a build script"))
}

fn main() {
    let source = Path::new(&cargo_var("CARGO_MANIFEST_DIR")).join("assets/ear-voxels.json");
    println!("cargo::rerun-if-changed={}", source.display());
    println!("cargo::rerun-if-changed=build.rs");

    let text = fs::read_to_string(&source).expect("assets/ear-voxels.json is readable");
    let root: serde_json::Value = serde_json::from_str(&text).expect("assets/ear-voxels.json parses as JSON");

    let dims = integers(&root["box_dims"], 3);
    let rig = &root["rig"];
    let contact = &root["contact_plane"];

    let voxels = root["voxels"].as_array().expect("`voxels` is an array");
    let mut table = String::with_capacity(voxels.len() * 24);
    for voxel in voxels {
        let entry = integers(voxel, 4);
        assert!(
            entry[0] < dims[0] && entry[1] < dims[1] && entry[2] < dims[2],
            "voxel {entry:?} escapes box_dims {dims:?}",
        );
        // `u8` is checked, not assumed: the grid is 15x24x16 and the class
        // vocabulary tops out at 11, but a re-extraction at a coarser
        // downsample could overflow, and a silent truncation there would
        // scramble the geometry rather than fail.
        assert!(entry.iter().all(|&v| u8::try_from(v).is_ok()), "voxel {entry:?} does not fit in u8");
        write!(table, "[{}, {}, {}, {}],", entry[0], entry[1], entry[2], entry[3]).expect("writing to a String");
    }

    let generated = format!(
        "// @generated by build.rs from assets/ear-voxels.json — do not edit.\n\
         pub const BOX_DIMS: [usize; 3] = [{}, {}, {}];\n\
         pub const RIG_BASE: [f32; 3] = {};\n\
         pub const RIG_TIP: [f32; 3] = {};\n\
         pub const RIG_AXIS: [f32; 3] = {};\n\
         pub const RIG_LENGTH: f32 = {};\n\
         pub const RIG_JOINT2: [f32; 3] = {};\n\
         pub const CONTACT_POINT: [f32; 3] = {};\n\
         pub const CONTACT_NORMAL: [f32; 3] = {};\n\
         pub const VOXELS: &[[u8; 4]] = &[{table}];\n",
        dims[0],
        dims[1],
        dims[2],
        triple(&rig["base"]),
        triple(&rig["tip"]),
        triple(&rig["axis"]),
        number(&rig["length"]),
        triple(&rig["joint2_at"]),
        triple(&contact["point"]),
        triple(&contact["normal"]),
    );

    let out = Path::new(&cargo_var("OUT_DIR")).join("ear_data.rs");
    fs::write(&out, generated).expect("the generated table is writable");
}

/// Read a JSON array of `count` non-negative integers.
fn integers(value: &serde_json::Value, count: usize) -> Vec<usize> {
    let array = value.as_array().expect("expected a JSON array of integers");
    assert_eq!(array.len(), count, "expected {count} integers, got {}", array.len());
    array
        .iter()
        .map(|entry| usize::try_from(entry.as_u64().expect("expected a non-negative integer")).expect("fits in usize"))
        .collect()
}

/// Render a JSON array of three numbers as an `[f32; 3]` literal.
fn triple(value: &serde_json::Value) -> String {
    let array = value.as_array().expect("expected a JSON array of three numbers");
    assert_eq!(array.len(), 3, "expected three numbers");
    format!("[{}, {}, {}]", number(&array[0]), number(&array[1]), number(&array[2]))
}

/// Render one JSON number as an `f32` literal. `{:?}` on `f32` round-trips, so
/// the emitted literal parses back to exactly the value written.
fn number(value: &serde_json::Value) -> String {
    #[allow(clippy::cast_possible_truncation)] // The dataset is authored at f32 precision.
    let narrowed = value.as_f64().expect("expected a number") as f32;
    format!("{narrowed:?}")
}
