//! Provider-adapter traits + stub impls shared by the two content-gen
//! caps (`aether.anthropic`, issue 1014; `aether.gemini`, issue 1015).
//!
//! The kind is the caller-stable contract; the adapter is the
//! vendor-compat layer (ADR-0050 §4). Each provider cap holds an
//! adapter trait object — a `ureq`-backed real impl in production, the
//! `Disabled*` fallback when its API key is absent, and one of the
//! `Stub*` impls below in CI smokes so no test reaches an external
//! service.
//!
//! The request / response shapes here are adapter-facing, not wire
//! kinds: the cap converts the wire kind (which lives in
//! `aether-kinds`) into the adapter request before dispatch and the
//! adapter response back into the wire reply. Keeping them here lets
//! issue 1013 land the stub-adapter scaffolding and a CI smoke before
//! either provider cap's kinds exist.

/// One generated text completion from an Anthropic adapter. Mirrors
/// the `aether.anthropic.*.send_result::Ok` payload minus the
/// wire-level `request_id` echo (the cap re-attaches that).
#[derive(Clone, Debug)]
pub struct AnthropicResponse {
    /// The assistant's reply text. For the Messages API this is the
    /// concatenated `text` content blocks; for the CLI it's stdout.
    pub text: String,
    /// The model the provider reports actually serving the request.
    pub model_used: String,
    /// Token + wall-clock accounting. Issue 1014 owns the wire `Usage`
    /// kind; the adapter layer carries the same four fields inline so
    /// this crate doesn't depend on `aether-kinds`' provider kinds
    /// before they exist.
    pub usage: AdapterUsage,
}

/// One generated media artifact from a Gemini adapter. The bytes are
/// staged to `save://gen/<uuid>.{png,wav}` by the cap (via
/// [`crate::shared::contentgen::staging::stage_gen_output`]); the adapter just
/// returns the raw bytes + extension.
#[derive(Clone, Debug)]
pub struct GeminiArtifact {
    /// The generated bytes (PNG for Nano Banana, WAV for Lyria).
    pub bytes: Vec<u8>,
    /// File extension without the dot — `"png"` or `"wav"`. Drives the
    /// staged filename suffix.
    pub ext: String,
}

/// One generated media response from a Gemini adapter. `artifacts` is
/// plural because Lyria's `sample_count` yields multiple clips.
#[derive(Clone, Debug, Default)]
pub struct GeminiResponse {
    /// Generated artifacts. Nano Banana returns exactly one; Lyria
    /// returns `sample_count` clips.
    pub artifacts: Vec<GeminiArtifact>,
    /// The model the provider reports actually serving the request.
    pub model_used: String,
    /// Wall-clock + (where the provider reports them) token / cost
    /// accounting.
    pub usage: AdapterUsage,
    /// NB2-only opaque signature the caller passes back unchanged for a
    /// multi-turn image edit. `None` for Lyria and older image models.
    pub thought_signature: Option<String>,
    /// Grounding metadata (search queries + source URLs) parsed from the
    /// response when `use_grounding` produced a `groundingMetadata`
    /// block. `(Vec<search_queries>, Vec<source_urls>)`; `None` when the
    /// block was absent. Kept as inline tuples so the shared adapter
    /// types don't depend on the provider kinds in `aether-kinds`.
    pub grounding: Option<(Vec<String>, Vec<String>)>,
}

/// Adapter-layer usage accounting. Carries the same four fields as the
/// wire `Usage` kind issue 1014 lands in `aether-kinds`, kept inline so
/// the shared adapter traits don't take a forward dependency on the
/// provider kinds.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct AdapterUsage {
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub wall_clock_ms: u32,
    pub cost_micros: Option<u64>,
}

/// Anthropic provider backend. Two methods, one per ADR-0050 routing
/// kind: `messages_send` (HTTPS to the official Messages API),
/// `cli_send` (the local `claude` subprocess against the user's
/// subscription). Both take a validated request and return the
/// completion or a structured error string the cap maps onto
/// `AnthropicError`.
///
/// The error type is `String` at the trait boundary so this module
/// stays free of the provider error enums (which live in
/// `aether-kinds`, landed by issue 1014); the cap converts the string
/// into the typed variant. The blocking call runs on issue 1013's
/// spawn-and-die ephemeral thread, never on the dispatcher.
pub trait AnthropicAdapter: Send + Sync {
    /// Run a Messages-API completion. Blocking (`ureq`); the cap calls
    /// this off the dispatcher thread.
    fn messages_send(&self, req: AnthropicRequest) -> Result<AnthropicResponse, String>;

    /// Run a `claude`-subprocess completion. Blocking
    /// (`std::process::Command`); the cap calls this off the dispatcher
    /// thread.
    fn cli_send(&self, req: AnthropicRequest) -> Result<AnthropicResponse, String>;

    /// The models this adapter's `model -> ApiShape` table accepts. The
    /// cap validates the request's `model` against this list *before*
    /// any dispatch and replies `UnknownModel { model, supported }`
    /// synchronously on a miss (ADR-0050). An empty list means "accept
    /// any model" — the disabled / CLI-passthrough adapters don't
    /// gate, since the CLI itself validates the model id.
    fn supported_models(&self) -> Vec<String> {
        Vec::new()
    }
}

/// Adapter-facing Anthropic completion request. The cap converts the
/// wire `aether.anthropic.*.send` kind into this before handing it to
/// the adapter. `model` selects the backend's `model -> ApiShape`
/// entry; `prompt` is the flattened user/system content.
#[derive(Clone, Debug)]
pub struct AnthropicRequest {
    pub model: String,
    pub prompt: String,
    pub system: Option<String>,
    pub max_tokens: Option<u32>,
    pub temperature: Option<f32>,
}

/// Gemini provider backend. Two methods, one per ADR-0050 media kind:
/// `nanobanana_generate` (image), `lyria_generate` (music). Both take a
/// validated request and return raw bytes the cap stages to
/// `save://gen/`.
pub trait GeminiAdapter: Send + Sync {
    /// Run a Nano Banana image generation. Blocking (`ureq`).
    fn nanobanana_generate(&self, req: GeminiImageRequest) -> Result<GeminiResponse, String>;

    /// Run a Lyria music generation. Blocking (`ureq`).
    fn lyria_generate(&self, req: GeminiMusicRequest) -> Result<GeminiResponse, String>;
}

/// Adapter-facing Nano Banana image request. The cap reads
/// reference-image bytes from the supplied paths and runs per-model
/// validation before constructing this; the adapter just dispatches the
/// HTTP call. `aspect_ratio` rides as the provider's `W:H` string;
/// `reference_images` are the already-read reference bytes.
#[derive(Clone, Debug, Default)]
pub struct GeminiImageRequest {
    pub model: String,
    pub prompt: String,
    /// Provider `W:H` aspect-ratio string (e.g. `"16:9"`).
    pub aspect_ratio: String,
    /// Provider image-size string (`"512"` / `"1K"` / `"2K"` / `"4K"`),
    /// `None` when the caller left `image_size` unset.
    pub image_size: Option<String>,
    /// Provider `thinkingLevel` string (`"minimal"` / `"high"`), `None`
    /// when the caller left `thinking_level` unset.
    pub thinking_level: Option<String>,
    /// `thinkingConfig.includeThoughts`, `None` when unset.
    pub include_thoughts: Option<bool>,
    /// Whether to add the `google_search` grounding tool.
    pub use_grounding: bool,
    /// Reference-image bytes the cap read from the supplied paths.
    pub reference_images: Vec<Vec<u8>>,
}

/// Adapter-facing Lyria music request.
#[derive(Clone, Debug)]
pub struct GeminiMusicRequest {
    pub model: String,
    pub prompt: String,
    /// How many clips to generate — drives the length of
    /// [`GeminiResponse::artifacts`].
    pub sample_count: u32,
}

/// A minimal 1×1 opaque-black PNG. Used by [`StubGeminiAdapter`] so the
/// staged image path decodes as a valid PNG without pulling the `png`
/// encoder into the base `native` feature. Hand-rolled: signature +
/// IHDR + a single zlib-stored IDAT + IEND, with precomputed CRCs.
pub const STUB_PNG: &[u8] = &[
    // PNG signature
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // IHDR chunk: 1x1, 8-bit grayscale
    0x00, 0x00, 0x00, 0x0D, // length 13
    0x49, 0x48, 0x44, 0x52, // "IHDR"
    0x00, 0x00, 0x00, 0x01, // width 1
    0x00, 0x00, 0x00, 0x01, // height 1
    0x08, 0x00, // bit depth 8, color type 0 (grayscale)
    0x00, 0x00, 0x00, // compression, filter, interlace
    0x3A, 0x7E, 0x9B, 0x55, // IHDR CRC
    // IDAT chunk: zlib stream wrapping one filtered scanline (filter
    // byte 0x00 + one pixel 0x00)
    0x00, 0x00, 0x00, 0x0C, // length 12
    0x49, 0x44, 0x41, 0x54, // "IDAT"
    0x08, 0xD7, // zlib header (CMF/FLG)
    0x63, 0x60, 0x00, 0x00, // stored deflate block for [0x00, 0x00]
    0x00, 0x02, 0x00, 0x01, // adler32 of the uncompressed data
    0x73, 0x75, 0x01, 0x18, // IDAT CRC
    // IEND chunk
    0x00, 0x00, 0x00, 0x00, // length 0
    0x49, 0x45, 0x4E, 0x44, // "IEND"
    0xAE, 0x42, 0x60, 0x82, // IEND CRC
];

/// A minimal silent mono 16-bit PCM WAV (RIFF/WAVE, 48 kHz, a single
/// zero sample). Used by [`StubGeminiAdapter`] so the staged audio path
/// decodes as a valid WAV. Hand-rolled header so this crate doesn't
/// pull a WAV encoder into the base `native` feature.
pub const STUB_WAV: &[u8] = &[
    // RIFF header
    0x52, 0x49, 0x46, 0x46, // "RIFF"
    0x26, 0x00, 0x00, 0x00, // chunk size = 38 (4 + 24 + 10)
    0x57, 0x41, 0x56, 0x45, // "WAVE"
    // fmt subchunk
    0x66, 0x6D, 0x74, 0x20, // "fmt "
    0x10, 0x00, 0x00, 0x00, // subchunk1 size = 16 (PCM)
    0x01, 0x00, // audio format = 1 (PCM)
    0x01, 0x00, // num channels = 1
    0x80, 0xBB, 0x00, 0x00, // sample rate = 48000
    0x00, 0x77, 0x01, 0x00, // byte rate = 96000
    0x02, 0x00, // block align = 2
    0x10, 0x00, // bits per sample = 16
    // data subchunk
    0x64, 0x61, 0x74, 0x61, // "data"
    0x02, 0x00, 0x00, 0x00, // subchunk2 size = 2 (one 16-bit sample)
    0x00, 0x00, // a single silent sample
];

/// No-op Anthropic adapter for CI smokes. Returns a canned completion
/// for both send paths so a smoke test can drive the dispatch loop
/// end-to-end with zero external cost.
pub struct StubAnthropicAdapter {
    /// The canned completion text both `messages_send` and `cli_send`
    /// return.
    pub canned_text: String,
}

impl Default for StubAnthropicAdapter {
    fn default() -> Self {
        Self {
            canned_text: String::from("stub completion"),
        }
    }
}

impl AnthropicAdapter for StubAnthropicAdapter {
    fn messages_send(&self, req: AnthropicRequest) -> Result<AnthropicResponse, String> {
        Ok(AnthropicResponse {
            text: self.canned_text.clone(),
            model_used: req.model,
            usage: AdapterUsage {
                input_tokens: 1,
                output_tokens: 1,
                wall_clock_ms: 0,
                cost_micros: Some(0),
            },
        })
    }

    fn cli_send(&self, req: AnthropicRequest) -> Result<AnthropicResponse, String> {
        Ok(AnthropicResponse {
            text: self.canned_text.clone(),
            model_used: req.model,
            usage: AdapterUsage {
                input_tokens: 0,
                output_tokens: 0,
                wall_clock_ms: 0,
                cost_micros: None,
            },
        })
    }
}

/// No-op Gemini adapter for CI smokes. Returns the fixed [`STUB_PNG`] /
/// [`STUB_WAV`] bytes so the cap can stage them and the returned path
/// both exists and decodes.
pub struct StubGeminiAdapter;

impl GeminiAdapter for StubGeminiAdapter {
    fn nanobanana_generate(&self, req: GeminiImageRequest) -> Result<GeminiResponse, String> {
        Ok(GeminiResponse {
            artifacts: vec![GeminiArtifact {
                bytes: STUB_PNG.to_vec(),
                ext: String::from("png"),
            }],
            model_used: req.model,
            usage: AdapterUsage::default(),
            thought_signature: None,
            grounding: None,
        })
    }

    fn lyria_generate(&self, req: GeminiMusicRequest) -> Result<GeminiResponse, String> {
        let count = req.sample_count.max(1) as usize;
        let artifacts = (0..count)
            .map(|_| GeminiArtifact {
                bytes: STUB_WAV.to_vec(),
                ext: String::from("wav"),
            })
            .collect();
        Ok(GeminiResponse {
            artifacts,
            model_used: req.model,
            usage: AdapterUsage::default(),
            thought_signature: None,
            grounding: None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{GeminiAdapter, GeminiMusicRequest, STUB_WAV, StubGeminiAdapter};

    #[test]
    fn stub_gemini_lyria_returns_sample_count_wavs() {
        let adapter = StubGeminiAdapter;
        let resp = adapter
            .lyria_generate(GeminiMusicRequest {
                model: String::from("lyria-test"),
                prompt: String::from("ambient"),
                sample_count: 3,
            })
            .expect("stub lyria is infallible");
        assert_eq!(resp.artifacts.len(), 3);
        for artifact in &resp.artifacts {
            assert_eq!(artifact.ext, "wav");
            assert_eq!(artifact.bytes, STUB_WAV);
            // RIFF magic + WAVE form type.
            assert_eq!(&artifact.bytes[..4], b"RIFF");
            assert_eq!(&artifact.bytes[8..12], b"WAVE");
        }
    }

    #[test]
    fn stub_gemini_lyria_zero_sample_count_yields_one_clip() {
        let adapter = StubGeminiAdapter;
        let resp = adapter
            .lyria_generate(GeminiMusicRequest {
                model: String::from("lyria-test"),
                prompt: String::from("ambient"),
                sample_count: 0,
            })
            .expect("stub lyria is infallible");
        assert_eq!(resp.artifacts.len(), 1);
    }
}
