//! Views over a contiguous journal prefix.
//!
//! [`Heads`] is the typed last-move fold. [`HeadHistory`] keeps every move,
//! so it answers the [`Heads`] of any earlier seq it has folded. [`Requests`]
//! and [`Activations`] fold the ADR-0226 driver records: outstanding program
//! requests and their dedup key, and per-head activation state. A [`View`]
//! consumes every entry in a batch, including kinds it ignores. There is no
//! `Clone` / `Send` / `Sync` bound. [`Publish`] is the opt-in owned snapshot
//! contract; it is not required of every view. This crate is `no_std` +
//! `alloc` and does not own a journal: callers supply entries, and the owner
//! of the fold enforces cursor and failure handling.
//!
//! Fixed aggregate views can keep ordinary Rust state and declare typed fold
//! methods. The cursor field is explicit, fallible handlers preserve their
//! error as a source, and filtering remains ordinary Rust inside the handler.
//!
//! ```
//! use std::convert::Infallible;
//! use std::collections::BTreeMap;
//!
//! use aether_bloomery_kinds::{HeadMoved, Tree};
//! use aether_bloomery_view::{View, ViewCursor, view};
//!
//! #[derive(Default)]
//! struct TreeMoves {
//!     cursor: ViewCursor,
//!     by_head: BTreeMap<String, u64>,
//! }
//!
//! #[view(cursor = cursor)]
//! impl View for TreeMoves {
//!     #[fold]
//!     fn moved(&mut self, event: HeadMoved<Tree>) -> Result<(), Infallible> {
//!         if event.head().as_str() == "ignored" {
//!             return Ok(());
//!         }
//!         *self.by_head.entry(event.head().as_str().into()).or_default() += 1;
//!         Ok(())
//!     }
//! }
//! ```
//!
//! Existing named guards project small values from the aggregate by declaring
//! it as their view dependency. The owner warms one `TreeMoves` instance and
//! lends it to every guard; the aggregate itself does not need `Clone` or
//! `Publish`.
//!
//! ```ignore
//! struct HeadMoveCount(u64);
//!
//! impl Guard<HeadMoved<Tree>> for HeadMoveCount {
//!     type Views = TreeMoves;
//!
//!     fn resolve(event: &HeadMoved<Tree>, moves: &TreeMoves) -> Option<Self> {
//!         moves.by_head.get(event.head().as_str()).copied().map(Self)
//!     }
//! }
//! ```
//!
//! ```
//! use aether_bloomery_kinds::Seq;
//! use aether_bloomery_view::Heads;
//!
//! let heads = Heads::new();
//! assert_eq!(heads.cursor(), Seq(0));
//! ```

#![no_std]
#![forbid(unsafe_code)]

extern crate alloc;

mod activations;
mod authoring;
mod heads;
mod history;
mod publish;
mod requests;
mod selection;
mod sequence;
mod view;

pub use activations::{ActivationFoldError, Activations, HeadActivation};
pub use aether_bloomery_view_derive::{fold, view};
pub use authoring::{ViewCursor, ViewFoldError};
pub use heads::{HeadFoldError, Heads};
pub use history::HeadHistory;
pub use publish::{Publish, PublishError};
pub use requests::{Outcome, Request, RequestFoldError, Requests};
pub use selection::{SelectedReactor, SelectionError, select_reactors};
pub use sequence::SequenceError;
pub use view::View;

/// Support used by code generated by [`macro@view`].
#[doc(hidden)]
pub mod __macro_internals {
    pub use crate::authoring::{ViewCursor, ViewFoldError, check_next};
    pub use aether_bloomery_kinds::{DecodeError, Entry, Seq};
    pub use aether_data::Storage;

    /// Decode one stored event without requiring codec traits in author scope.
    pub fn decode<K: Storage>(entry: &Entry) -> Result<K, DecodeError> {
        entry.decode()
    }
}
