[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
cargo_metadata = "0.23.1"
clap = { workspace = true }
determinator = "0.12.0"
guppy = "0.17.26"
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true }

[lints]
workspace = true
