//! Wavefront OBJ writer for the spike's mesher output.
//!
//! OBJ is the simplest text format every 3D viewer can open (Preview.app on
//! macOS, Blender, MeshLab, …). For spike measurability this beats stdout
//! triangle dumps — you can actually look at the mesh.
//!
//! Per-face color is not standard OBJ; we emit one OBJ group per palette
//! index so a viewer that supports groups can recolor manually.

use std::fmt::Write;

use crate::mesh::Triangle;
use aether_math::Vec3;

pub fn to_obj(triangles: &[Triangle]) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by dsl-mesh-spike").unwrap();
    writeln!(out, "# {} triangles", triangles.len()).unwrap();

    // Vertex deduplication keeps the file small and viewer-friendly.
    let mut vertex_index: Vec<Vec3> = Vec::new();
    let lookup = |verts: &mut Vec<Vec3>, v: Vec3| -> usize {
        if let Some(i) = verts.iter().position(|existing| approx_eq(*existing, v)) {
            return i + 1;
        }
        verts.push(v);
        verts.len()
    };

    let mut faces: Vec<(usize, [usize; 3], u32)> = Vec::with_capacity(triangles.len());
    for (i, tri) in triangles.iter().enumerate() {
        let a = lookup(&mut vertex_index, tri.vertices[0]);
        let b = lookup(&mut vertex_index, tri.vertices[1]);
        let c = lookup(&mut vertex_index, tri.vertices[2]);
        faces.push((i, [a, b, c], tri.color));
    }

    for v in &vertex_index {
        writeln!(out, "v {} {} {}", v.x, v.y, v.z).unwrap();
    }

    let mut faces_by_color = std::collections::BTreeMap::<u32, Vec<[usize; 3]>>::new();
    for (_, indices, color) in faces {
        faces_by_color.entry(color).or_default().push(indices);
    }

    for (color, indices_list) in faces_by_color {
        writeln!(out, "g palette_{color}").unwrap();
        for [a, b, c] in indices_list {
            writeln!(out, "f {a} {b} {c}").unwrap();
        }
    }

    out
}

fn approx_eq(a: Vec3, b: Vec3) -> bool {
    const EPS: f32 = 1e-6;
    (a.x - b.x).abs() < EPS && (a.y - b.y).abs() < EPS && (a.z - b.z).abs() < EPS
}
