//! The ADR-0159 `aether.gemini` guest component: a wasm `WasmActor` that
//! keeps the wire kinds byte-identical, reuses the shared pure logic
//! (`body` / `nanobanana` / `lyria` / `error`), and reaches every I/O site by
//! mail instead of owning a socket:
//!
//! - **HTTPS** → `aether.http.fetch` (ADR-0158). The component builds the
//!   provider request body with the ported builder, mails a `Fetch`, and
//!   feeds the `FetchResult` body to the ported parser. It queues nothing
//!   guest-side — the per-sender bound lives at the `aether.http` edge, so a
//!   guest holds no engine-side settlement hold and reopens no
//!   premature-settlement window (ADR-0158 §8).
//! - **Artifact staging** → `aether.fs.write` to `gen/<name>.{png,wav}` under
//!   the `save` namespace. Generated bytes never ride the reply; the reply
//!   carries the staged path (`feedback_no_bytes_in_llm_json`).
//! - **Reference-image reads** → `aether.fs.read`, one read per
//!   `object_reference_paths` / `character_reference_paths` entry before the
//!   Nano Banana fetch.
//!
//! Each request/reply flow is the ADR-0139 `send_with_context` /
//! `take_context` two-handler shape the mesh viewer runs: the request handler
//! stashes a kind-typed context carrying the original caller's `ReplyHandle`
//! and the request's `request_id`, and each reply handler recovers it, runs
//! the pure step, and either dispatches the next leg or replies the provider
//! `_result` kind. The chains are:
//!
//! - Nano Banana: `[read ×N →]` `fetch` → `write` → caller reply.
//! - Lyria: `fetch` → `write ×N` (one per clip) → caller reply.
//!
//! Because `send_with_context` inherits the handler's causal chain (ADR-0080
//! §7), the whole chain stays open engine-side until the final reply settles;
//! the guest holds only the small bookkeeping contexts between legs.

use aether_actor::{ActorInitError, Manual, OutboundReply, ReplyHandle, WasmActor, WasmCtx, WasmInitCtx, actor};
use aether_fs::{FsCapability, Read, ReadResult, Write, WriteResult};
use aether_http::{Fetch, FetchResult, HttpCapability, HttpError, HttpHeader, HttpMethod};
use aether_kinds::Usage;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::adapter::GeminiImageRequest;

use super::body::{
    aspect_ratio_str, build_lyria_body, build_nanobanana_body, genlang_url, image_size_str, thinking_level_str,
};
use super::{error, lyria, nanobanana};
use crate::{
    GeminiError, GroundingMetadata, LyriaGenerate, LyriaGenerateResult, NanobananaGenerate, NanobananaGenerateResult,
};

/// The `save`-namespace both the reference-read and the artifact-staging legs
/// address (ADR-0159 §3). Staged paths are namespace-relative, so a caller
/// reads a result back with `aether.fs.read { namespace: "save", path }`.
const SAVE_NAMESPACE: &str = "save";

/// Init-config for [`GeminiComponent`] (ADR-0090 init-config bytes; ADR-0159
/// §5). Carries the provider secret and tuning the chassis used to resolve
/// natively — the API key, the disable flag, the per-request timeout, and the
/// namespace-relative staging directory the chassis-side gen-root resolution
/// can no longer run for a guest.
///
/// # Agent
/// Encode one of these to the component's `Config` shape and pass it as the
/// `config` bytes of the `aether.component.load` that instantiates the
/// component (or `load_component`'s `config_path`). Omitting config bytes boots
/// [`GeminiComponentConfig::default()`]: no key (so every request replies
/// `Unauthorized`), a 180 s timeout, and the `gen` staging directory.
#[derive(aether_data::Kind, aether_data::Schema, Serialize, Deserialize, Debug, Clone)]
#[kind(name = "aether.gemini.config")]
pub struct GeminiComponentConfig {
    /// Google Gemini API key, sent as the `x-goog-api-key` header on each
    /// fetch. Empty leaves the provider disabled — every request replies
    /// `Err { Unauthorized }`, mirroring the native cap's key-absent boot.
    pub api_key: String,
    /// Disable the provider even when a key is present. Forces the
    /// `Unauthorized` reply.
    pub disabled: bool,
    /// Per-request timeout in milliseconds, passed as `Fetch.timeout_ms`. `0`
    /// defers to the `aether.http` chassis default (`AETHER_HTTP_TIMEOUT_MS`).
    pub timeout_millis: u32,
    /// Namespace-relative staging directory under the `save` namespace
    /// artifacts land in (`<gen_root>/<name>.{png,wav}`). Default `gen`, which
    /// keeps reply paths at `gen/<name>.…` — the same shape the native cap
    /// staged and readable through the `save` namespace.
    pub gen_root: String,
}

impl Default for GeminiComponentConfig {
    fn default() -> Self {
        Self {
            api_key: String::new(),
            disabled: false,
            timeout_millis: crate::DEFAULT_TIMEOUT_MILLIS,
            gen_root: String::from("gen"),
        }
    }
}

/// Which provider flow a `fetch` / `write` reply belongs to. The reply kinds
/// (`FetchResult` / `WriteResult`) are shared across both flows, so the
/// stashed context carries the discriminator plus the fields the reply needs.
#[derive(aether_data::Schema, Serialize, Deserialize, Debug, Clone)]
enum FetchFlow {
    Nanobanana { include_sig: bool, model_used: String },
    Lyria { model_used: String },
}

/// Context stashed on the outbound `aether.http.fetch`, recovered in
/// [`GeminiComponent::on_fetch_result`].
#[derive(aether_data::Kind, aether_data::Schema, Serialize, Deserialize, Debug, Clone)]
#[kind(name = "aether.gemini.fetch_context")]
struct FetchContext {
    reply: Option<ReplyHandle>,
    request_id: u64,
    flow: FetchFlow,
}

/// Context stashed on each reference-image `aether.fs.read`, recovered in
/// [`GeminiComponent::on_read_result`]. Threaded sequentially: each reply
/// pushes the read bytes into `acc_images` and either reads the next
/// `remaining_paths` entry or dispatches the Nano Banana fetch.
#[derive(aether_data::Kind, aether_data::Schema, Serialize, Deserialize, Debug, Clone)]
#[kind(name = "aether.gemini.read_context")]
struct ReadContext {
    reply: Option<ReplyHandle>,
    request_id: u64,
    include_sig: bool,
    model: String,
    prompt: String,
    /// Provider `W:H` aspect-ratio string (already mapped off the wire enum).
    aspect_ratio: String,
    image_size: Option<String>,
    thinking_level: Option<String>,
    include_thoughts: Option<bool>,
    use_grounding: bool,
    /// Reference paths not yet read.
    remaining_paths: Vec<String>,
    /// Reference bytes already read, in request order.
    acc_images: Vec<Vec<u8>>,
}

/// Which provider flow a `write` reply belongs to.
#[derive(aether_data::Schema, Serialize, Deserialize, Debug, Clone)]
enum WriteFlow {
    /// A single staged image; the reply fields are ready once the write lands.
    Nanobanana { model_used: String, thought_signature: Option<String>, grounding: Option<GroundingMetadata> },
    /// A clip-at-a-time staging chain; `remaining_clips` still to write,
    /// `acc_paths` staged so far.
    Lyria { model_used: String, remaining_clips: Vec<Vec<u8>>, acc_paths: Vec<String> },
}

/// Context stashed on each artifact `aether.fs.write`, recovered in
/// [`GeminiComponent::on_write_result`].
#[derive(aether_data::Kind, aether_data::Schema, Serialize, Deserialize, Debug, Clone)]
#[kind(name = "aether.gemini.write_context")]
struct WriteContext {
    reply: Option<ReplyHandle>,
    request_id: u64,
    flow: WriteFlow,
}

/// The `aether.gemini` guest component (ADR-0159).
///
/// # Agent
/// `load_component` this binary with a [`GeminiComponentConfig`] carrying the
/// API key, then send `aether.gemini.nanobanana.generate` (image) or
/// `aether.gemini.lyria.generate` (music) to its loaded lineage address and
/// send-and-await the `*_result` reply. `Ok` carries staged
/// `gen/<name>.{png,wav}` path(s) under the `save` namespace; read them back
/// through `aether.fs.read`. Requires the `aether.http` egress cap (with the
/// provider host allowlisted) and the `aether.fs` cap composed on the substrate.
pub struct GeminiComponent {
    config: GeminiComponentConfig,
    /// Monotonic per-instance counter for staged filenames — the guest has no
    /// wasm-safe UUID source, so `gen/<request_id>-<seq>.<ext>` gives a unique
    /// name without host randomness.
    next_seq: u64,
}

#[actor]
impl WasmActor for GeminiComponent {
    type Config = GeminiComponentConfig;
    const NAMESPACE: &'static str = "aether.gemini";

    fn init(config: GeminiComponentConfig, _ctx: &mut WasmInitCtx<'_>) -> Result<Self, ActorInitError> {
        Ok(Self { config, next_seq: 0 })
    }

    /// Request an image from the Nano Banana family (ADR-0050). Validates the
    /// model and the per-model `aspect_ratio` / `image_size` / reference-count
    /// rules synchronously, then reads any reference images and dispatches the
    /// fetch.
    ///
    /// # Agent
    /// Reply: `NanobananaGenerateResult` carrying a staged, `save`-relative
    /// `gen/<name>.png` path.
    #[handler::manual]
    fn on_nanobanana_generate(&mut self, ctx: &mut WasmCtx<'_, Manual>, mail: NanobananaGenerate) {
        let request_id = mail.request_id;
        let include_sig = mail.include_thought_signature.unwrap_or(false);

        let Some(shape) = nanobanana::lookup_model(&mail.model) else {
            ctx.reply(&NanobananaGenerateResult::Err {
                request_id,
                error: GeminiError::UnknownModel { model: mail.model, supported: nanobanana::supported_model_ids() },
            });
            return;
        };
        let inputs = nanobanana::ValidationInputs {
            aspect_ratio: mail.aspect_ratio,
            image_size: mail.image_size,
            thinking_level_set: mail.thinking_level.is_some(),
            include_thoughts_set: mail.include_thoughts.is_some(),
            use_grounding_set: mail.use_grounding.is_some(),
            object_ref_count: mail.object_reference_paths.len(),
            character_ref_count: mail.character_reference_paths.len(),
        };
        if let Err(error) = nanobanana::validate(shape, &inputs) {
            ctx.reply(&NanobananaGenerateResult::Err { request_id, error });
            return;
        }

        if self.is_disabled() {
            ctx.reply(&NanobananaGenerateResult::Err { request_id, error: GeminiError::Unauthorized });
            return;
        }

        let mut remaining_paths = mail.object_reference_paths;
        remaining_paths.extend(mail.character_reference_paths);
        let read_ctx = ReadContext {
            reply: ctx.reply_target(),
            request_id,
            include_sig,
            model: mail.model,
            prompt: mail.prompt,
            aspect_ratio: aspect_ratio_str(mail.aspect_ratio).to_string(),
            image_size: mail.image_size.map(|s| image_size_str(s).to_string()),
            thinking_level: mail.thinking_level.map(|l| thinking_level_str(l).to_string()),
            include_thoughts: mail.include_thoughts,
            use_grounding: mail.use_grounding.unwrap_or(false),
            remaining_paths,
            acc_images: Vec::new(),
        };
        self.step_reference_reads(ctx, read_ctx);
    }

    /// Request music from the Lyria family (ADR-0050). Rejects an unknown
    /// model and a both-set `seed` + `sample_count` synchronously, then
    /// dispatches the fetch.
    ///
    /// # Agent
    /// Reply: `LyriaGenerateResult` carrying one staged, `save`-relative
    /// `gen/<name>.wav` path per clip.
    #[handler::manual]
    fn on_lyria_generate(&mut self, ctx: &mut WasmCtx<'_, Manual>, mail: LyriaGenerate) {
        let request_id = mail.request_id;

        if !lyria::is_supported(&mail.model) {
            ctx.reply(&LyriaGenerateResult::Err {
                request_id,
                error: GeminiError::UnknownModel { model: mail.model, supported: lyria::supported_model_ids() },
            });
            return;
        }
        if let Err(error) = lyria::validate(&mail.model, mail.seed.is_some(), mail.sample_count.is_some()) {
            ctx.reply(&LyriaGenerateResult::Err { request_id, error });
            return;
        }

        if self.is_disabled() {
            ctx.reply(&LyriaGenerateResult::Err { request_id, error: GeminiError::Unauthorized });
            return;
        }

        let body = build_lyria_body(&mail.prompt, mail.sample_count.unwrap_or(1));
        let fetch = self.build_fetch(request_id, &mail.model, "predict", &body);
        let fetch_ctx =
            FetchContext { reply: ctx.reply_target(), request_id, flow: FetchFlow::Lyria { model_used: mail.model } };
        let _ = ctx.actor::<HttpCapability>().send_with_context(&fetch, &fetch_ctx);
    }

    /// Consume one reference-image read reply. Pushes the bytes and reads the
    /// next reference, or dispatches the Nano Banana fetch once all references
    /// are in hand. A read failure aborts the request with an `AdapterError`.
    ///
    /// # Agent
    /// Substrate-driven; do not send manually.
    #[handler::manual]
    fn on_read_result(&mut self, ctx: &mut WasmCtx<'_, Manual>, r: ReadResult) {
        let Some(mut read_ctx) = ctx.take_context::<ReadContext>() else {
            return;
        };
        match r {
            ReadResult::Ok { bytes, .. } => {
                read_ctx.acc_images.push(bytes);
                self.step_reference_reads(ctx, read_ctx);
            }
            ReadResult::Err { path, error, .. } => {
                Self::reply_error(
                    ctx,
                    read_ctx.reply,
                    read_ctx.request_id,
                    true,
                    GeminiError::AdapterError(format!("reference {path}: {error:?}")),
                );
            }
        }
    }

    /// Consume the provider HTTP reply. On a 2xx, parses the artifact bytes and
    /// begins staging; otherwise maps the status / transport error to the
    /// provider taxonomy and replies.
    ///
    /// # Agent
    /// Substrate-driven; do not send manually.
    #[handler::manual]
    fn on_fetch_result(&mut self, ctx: &mut WasmCtx<'_, Manual>, r: FetchResult) {
        let Some(fetch_ctx) = ctx.take_context::<FetchContext>() else {
            return;
        };
        let is_nanobanana = matches!(fetch_ctx.flow, FetchFlow::Nanobanana { .. });
        match r {
            FetchResult::Ok { status, headers, body, .. } => {
                let text = String::from_utf8_lossy(&body);
                if !(200..300).contains(&status) {
                    let error = error::status_to_error(status, retry_after_millis(&headers), &text);
                    Self::reply_error(ctx, fetch_ctx.reply, fetch_ctx.request_id, is_nanobanana, error);
                    return;
                }
                match fetch_ctx.flow {
                    FetchFlow::Nanobanana { include_sig, model_used } => {
                        self.stage_nanobanana(
                            ctx,
                            fetch_ctx.reply,
                            fetch_ctx.request_id,
                            include_sig,
                            model_used,
                            &text,
                        );
                    }
                    FetchFlow::Lyria { model_used } => {
                        self.stage_lyria(ctx, fetch_ctx.reply, fetch_ctx.request_id, model_used, &text);
                    }
                }
            }
            FetchResult::Err { error, .. } => {
                Self::reply_error(ctx, fetch_ctx.reply, fetch_ctx.request_id, is_nanobanana, map_http_error(error));
            }
        }
    }

    /// Consume an artifact-staging reply. Replies the provider `_result` to the
    /// original caller (Nano Banana, or the last Lyria clip) or writes the next
    /// Lyria clip.
    ///
    /// # Agent
    /// Substrate-driven; do not send manually.
    #[handler::manual]
    fn on_write_result(&mut self, ctx: &mut WasmCtx<'_, Manual>, r: WriteResult) {
        let Some(write_ctx) = ctx.take_context::<WriteContext>() else {
            return;
        };
        let request_id = write_ctx.request_id;
        let reply = write_ctx.reply;
        match r {
            WriteResult::Ok { path, .. } => match write_ctx.flow {
                WriteFlow::Nanobanana { model_used, thought_signature, grounding } => {
                    Self::maybe_reply(
                        ctx,
                        reply,
                        &NanobananaGenerateResult::Ok {
                            request_id,
                            output_path: path,
                            model_used,
                            usage: default_usage(),
                            thought_signature,
                            grounding,
                        },
                    );
                }
                WriteFlow::Lyria { model_used, remaining_clips, mut acc_paths } => {
                    acc_paths.push(path);
                    if remaining_clips.is_empty() {
                        Self::maybe_reply(
                            ctx,
                            reply,
                            &LyriaGenerateResult::Ok {
                                request_id,
                                output_paths: acc_paths,
                                model_used,
                                usage: default_usage(),
                            },
                        );
                    } else {
                        self.write_next_clip(ctx, reply, request_id, model_used, remaining_clips, acc_paths);
                    }
                }
            },
            WriteResult::Err { error, .. } => {
                let is_nanobanana = matches!(write_ctx.flow, WriteFlow::Nanobanana { .. });
                Self::reply_error(
                    ctx,
                    reply,
                    request_id,
                    is_nanobanana,
                    GeminiError::AdapterError(format!("stage artifact: {error:?}")),
                );
            }
        }
    }
}

impl GeminiComponent {
    /// Whether every request should short-circuit to `Unauthorized` — no key,
    /// or explicitly disabled.
    fn is_disabled(&self) -> bool {
        self.config.disabled || self.config.api_key.is_empty()
    }

    /// Per-request timeout for `Fetch.timeout_ms`; `0` defers to the http
    /// chassis default.
    fn timeout_ms(&self) -> Option<u32> {
        (self.config.timeout_millis != 0).then_some(self.config.timeout_millis)
    }

    /// The next unique staged filename under the configured `gen_root`.
    fn next_name(&mut self, request_id: u64, ext: &str) -> String {
        self.next_seq += 1;
        format!("{}/{}-{}.{}", self.config.gen_root, request_id, self.next_seq, ext)
    }

    /// Build a Generative Language API `POST` fetch for `model`'s `endpoint`.
    fn build_fetch(&self, request_id: u64, model: &str, endpoint: &str, body: &Value) -> Fetch {
        Fetch {
            request_id,
            url: genlang_url(model, endpoint),
            method: HttpMethod::Post,
            headers: vec![
                HttpHeader { name: String::from("x-goog-api-key"), value: self.config.api_key.clone() },
                HttpHeader { name: String::from("content-type"), value: String::from("application/json") },
            ],
            body: serde_json::to_vec(body).unwrap_or_default(),
            timeout_ms: self.timeout_ms(),
        }
    }

    /// Read the next reference image, or — once none remain — build the Nano
    /// Banana request from the accumulated bytes and dispatch the fetch.
    fn step_reference_reads(&self, ctx: &mut WasmCtx<'_, Manual>, read_ctx: ReadContext) {
        if let Some((next, rest)) = read_ctx.remaining_paths.split_first() {
            let read = Read { namespace: String::from(SAVE_NAMESPACE), path: next.clone() };
            let stash = ReadContext { remaining_paths: rest.to_vec(), ..read_ctx };
            let _ = ctx.actor::<FsCapability>().send_with_context(&read, &stash);
            return;
        }

        let image_req = GeminiImageRequest {
            prompt: read_ctx.prompt,
            aspect_ratio: read_ctx.aspect_ratio,
            image_size: read_ctx.image_size,
            thinking_level: read_ctx.thinking_level,
            include_thoughts: read_ctx.include_thoughts,
            use_grounding: read_ctx.use_grounding,
            reference_images: read_ctx.acc_images,
        };
        let body = build_nanobanana_body(&image_req);
        let fetch = self.build_fetch(read_ctx.request_id, &read_ctx.model, "generateContent", &body);
        let fetch_ctx = FetchContext {
            reply: read_ctx.reply,
            request_id: read_ctx.request_id,
            flow: FetchFlow::Nanobanana { include_sig: read_ctx.include_sig, model_used: read_ctx.model },
        };
        let _ = ctx.actor::<HttpCapability>().send_with_context(&fetch, &fetch_ctx);
    }

    /// Parse the Nano Banana response, gate the thought signature by the
    /// caller's flag, and stage the image through `aether.fs.write`.
    fn stage_nanobanana(
        &mut self,
        ctx: &mut WasmCtx<'_, Manual>,
        reply: Option<ReplyHandle>,
        request_id: u64,
        include_sig: bool,
        model_used: String,
        text: &str,
    ) {
        let parsed = match nanobanana::parse_image_response(text) {
            Ok(p) => p,
            Err(e) => {
                Self::reply_error(ctx, reply, request_id, true, GeminiError::AdapterError(e));
                return;
            }
        };
        // Opt-in / default-off: clear the (multi-MB) signature unless the
        // caller asked to retain it for a multi-turn continuation.
        let thought_signature = if include_sig {
            parsed.thought_signature
        } else {
            None
        };
        let grounding =
            parsed.grounding.map(|(search_queries, source_urls)| GroundingMetadata { search_queries, source_urls });

        let path = self.next_name(request_id, "png");
        let write = Write { namespace: String::from(SAVE_NAMESPACE), path, bytes: parsed.bytes };
        let write_ctx = WriteContext {
            reply,
            request_id,
            flow: WriteFlow::Nanobanana { model_used, thought_signature, grounding },
        };
        let _ = ctx.actor::<FsCapability>().send_with_context(&write, &write_ctx);
    }

    /// Parse the Lyria response into clips and begin staging them one at a time.
    fn stage_lyria(
        &mut self,
        ctx: &mut WasmCtx<'_, Manual>,
        reply: Option<ReplyHandle>,
        request_id: u64,
        model_used: String,
        text: &str,
    ) {
        let clips = match lyria::parse_clip_response(text) {
            Ok(c) => c,
            Err(e) => {
                Self::reply_error(ctx, reply, request_id, false, GeminiError::AdapterError(e));
                return;
            }
        };
        // `parse_clip_response` guarantees at least one clip.
        self.write_next_clip(ctx, reply, request_id, model_used, clips, Vec::new());
    }

    /// Write the head of `remaining_clips`, carrying the rest and the staged
    /// paths so far forward in the write context.
    fn write_next_clip(
        &mut self,
        ctx: &mut WasmCtx<'_, Manual>,
        reply: Option<ReplyHandle>,
        request_id: u64,
        model_used: String,
        mut remaining_clips: Vec<Vec<u8>>,
        acc_paths: Vec<String>,
    ) {
        let clip = remaining_clips.remove(0);
        let path = self.next_name(request_id, "wav");
        let write = Write { namespace: String::from(SAVE_NAMESPACE), path, bytes: clip };
        let write_ctx =
            WriteContext { reply, request_id, flow: WriteFlow::Lyria { model_used, remaining_clips, acc_paths } };
        let _ = ctx.actor::<FsCapability>().send_with_context(&write, &write_ctx);
    }

    /// Reply the flow's `_result::Err` to the original caller (if any).
    fn reply_error(
        ctx: &mut WasmCtx<'_, Manual>,
        reply: Option<ReplyHandle>,
        request_id: u64,
        is_nanobanana: bool,
        error: GeminiError,
    ) {
        if is_nanobanana {
            Self::maybe_reply(ctx, reply, &NanobananaGenerateResult::Err { request_id, error });
        } else {
            Self::maybe_reply(ctx, reply, &LyriaGenerateResult::Err { request_id, error });
        }
    }

    /// Reply `payload` to a stashed handle, or drop it for a fire-and-forget
    /// original request that carried no reply target.
    fn maybe_reply<K: aether_data::Kind>(ctx: &mut WasmCtx<'_, Manual>, reply: Option<ReplyHandle>, payload: &K) {
        if let Some(handle) = reply {
            ctx.reply_to(handle, payload);
        }
    }
}

/// The zero `Usage` the guest reports — the Gemini media APIs return no token
/// accounting.
fn default_usage() -> Usage {
    Usage { input_tokens: 0, output_tokens: 0, wall_clock_millis: 0, cost_micros: None }
}

/// Parse a `retry-after` response header (seconds) into milliseconds.
fn retry_after_millis(headers: &[HttpHeader]) -> Option<u32> {
    headers
        .iter()
        .find(|h| h.name.eq_ignore_ascii_case("retry-after"))
        .and_then(|h| h.value.trim().parse::<u32>().ok())
        .map(|secs| secs.saturating_mul(1000))
}

/// Map an `aether.http` transport error onto the provider taxonomy. Every
/// `HttpError` is an infrastructure failure rather than a provider verdict, so
/// each lands in `AdapterError` with a message naming the knob an operator
/// tunes — `BodyTooLarge` in particular flags the `AETHER_HTTP_MAX_BODY_BYTES`
/// ceiling a large 4K render or multi-clip response can exceed (ADR-0159
/// implementation gate).
fn map_http_error(error: HttpError) -> GeminiError {
    let detail = match error {
        HttpError::InvalidUrl(url) => format!("invalid url: {url}"),
        HttpError::Timeout => String::from("http request timed out"),
        HttpError::BodyTooLarge => {
            String::from("provider response exceeded the http body cap (raise AETHER_HTTP_MAX_BODY_BYTES)")
        }
        HttpError::AllowlistDenied => String::from("provider host not allowlisted (set AETHER_HTTP_ALLOWLIST)"),
        HttpError::Disabled => String::from("http egress is disabled on this substrate"),
        HttpError::AdapterError(detail) => detail,
    };
    GeminiError::AdapterError(detail)
}

aether_actor::export!(GeminiComponent);
