//! `aether.gemini` cap (ADR-0050). One chassis-owned mailbox exposing
//! two media-generation request kinds — `aether.gemini.nanobanana.generate`
//! (image) and `aether.gemini.lyria.generate` (music). No text
//! completion (the user defaults to the Claude CLI per ADR-0050 §3).
//!
//! Like `aether.anthropic` (issue 1014), long-tail calls ride the
//! ADR-0093 hold-until-resolve dispatch: the generate handler submits the
//! blocking `ureq` call to a [`TaskQueue`](crate::shared::contentgen::TaskQueue)
//! (`ctx.dispatch_blocking`), so an ephemeral worker runs the call and
//! stages the generated bytes to `save://gen/<uuid>.{png,wav}` (binary
//! outputs never ride the mail wire); the completion routes back to the
//! cap's `#[handler(task)]` as a `TaskDone` carrying the staged result.
//! Per-model validation of `aspect_ratio` / `image_size` / reference-path
//! counts (image) and `seed` / `sample_count` exclusivity (music) runs
//! synchronously on the dispatcher thread *before* any dispatch.
//!
//! A key-absent boot wires [`DisabledGeminiAdapter`] so the mailbox
//! still loads and replies `Err { Unauthorized }`. CI smokes wire the
//! `StubGeminiAdapter` from issue 1013.
//!
//! Per ADR-0121 the cap owns its mail kinds — the request / result types
//! and their supporting enums live in `kinds`, decomposed alongside the
//! `config`, `adapter`, and `capability` seams.

mod adapter;
mod capability;
mod config;
mod error;
mod kinds;
mod lyria;
mod nanobanana;

// The `aether.gemini` runtime half (ADR-0122 identity/runtime split): the
// `aether_substrate`-typed state + reply helpers the `#[actor] impl` in
// `capability` reaches through `use super::runtime::*`. Gated once here so a
// transport-only build of the `GeminiCapability` identity never names the
// state nor pulls `aether_substrate` through this cap.
#[cfg(feature = "runtime")]
mod runtime;

pub use adapter::{DisabledGeminiAdapter, UreqGeminiAdapter};
pub use capability::GeminiCapability;
pub use config::{GeminiConfig, GeminiConfigLayer, GeminiOverlay};
pub use kinds::*;

/// Default per-cap concurrency bound when `AETHER_GEMINI_MAX_IN_FLIGHT`
/// is unset. Conservative — image / music generation is multi-second
/// and paid.
pub const DEFAULT_MAX_IN_FLIGHT: usize = 2;

/// Default per-request timeout when `AETHER_GEMINI_TIMEOUT_MS` is unset.
/// Media generation can run a couple minutes.
pub const DEFAULT_TIMEOUT_MILLIS: u32 = 180_000;
